# Generated by Django 6.0.2 on 2026-02-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('type_projet', models.CharField(choices=[('site_vitrine', 'Site Vitrine'), ('app_web', 'Application Web'), ('script', 'Script / Automatisation'), ('autre', 'Autre')], max_length=50)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='technologies/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description_courte', models.TextField(max_length=200)),
                ('description_longue', models.TextField()),
                ('image_principale', models.ImageField(upload_to='projects/main/')),
                ('lien_github', models.URLField(blank=True)),
                ('lien_demo', models.URLField(blank=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateField(auto_now=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('est_publie', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='portfolio.category')),
                ('galerie_images', models.ManyToManyField(blank=True, related_name='projets', to='portfolio.imageprojet')),
                ('technologies', models.ManyToManyField(related_name='projets', to='portfolio.technology')),
            ],
        ),
    ]
