# Generated by Django 6.0.2 on 2026-02-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description_longue',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_courte',
        ),
        migrations.RemoveField(
            model_name='project',
            name='galerie_images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ordre_affichage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='technologie',
            field=models.CharField(default='', help_text='Technologie principale utilisée', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
