# Generated by GPT-5.2 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_align_schema_current_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/main/"),
        ),
    ]

