# Generated by Django 6.0.2 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_project_image_to_imagefield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="demo_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]

