# Generated by Django 6.0.2 on 2026-07-10 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_demo_link_alter_project_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, help_text='Lien vers la démo en ligne', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='Lien vers le repository GitHub', null=True),
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visitor_id', models.UUIDField(db_index=True, help_text='Identifiant unique du visiteur (localStorage)')),
                ('event_type', models.CharField(choices=[('home', 'Home Page View'), ('project_detail', 'Project Detail View'), ('github_click', 'GitHub Link Click'), ('demo_click', 'Demo Link Click')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('country', models.CharField(blank=True, db_index=True, help_text='Code pays ISO 3166-1 alpha-2', max_length=2)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(help_text='IP du visiteur (non exposée publiquement)')),
                ('project', models.ForeignKey(blank=True, help_text='Projet concerné (null pour home)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='portfolio.project')),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'visitor_id'], name='idx_analytics_time_visitor'), models.Index(fields=['project', 'event_type'], name='idx_analytics_project_event'), models.Index(fields=['country'], name='idx_analytics_country')],
            },
        ),
    ]
