# Generated by Django 6.0.2 on 2026-09-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_contactmessage_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology_used',
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.technology'),
        ),
    ]
