# Generated by Django 6.0.2 on 2026-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_project_technology_used_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(blank=True, default='', help_text='Fourchette de budget (optionnel)', max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='telephone',
            field=models.CharField(blank=True, default='', help_text='Numéro de téléphone (optionnel)', max_length=20),
        ),
    ]
