# Generated by Django 6.0.2 on 2026-09-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_contactmessage_budget_contactmessage_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='budget',
        ),
    ]
